[build-system]
requires = ['setuptools >= 40.8.0']
build-backend='setuptools.build_meta'

[tool.black]
target-version=['py312']
force-exclude='tests'

[tool.isort]
profile='black'
default_section='THIRDPARTY'
known_first_party='seahorse'